# -*- coding: utf-8 -*-
"""Stochastic least-cost paths (Lewis 2021).

Two sources of uncertainty are modelled and combined over N Monte-Carlo
realisations to produce a *probabilistic corridor* — the fraction of iterations
in which each cell lies on the least-cost path:

* **DEM error** — a vertical-accuracy (RMSE) error field is added to the DEM
  each iteration, so the slope (and therefore the cost surface) varies.
* **Global stochasticity** — edges are randomly dropped each iteration, modelling
  unmodelled local impassability.

Both are pure numpy/scipy and reuse the deterministic core (`build_conductance`,
`least_cost_path`), so there is no duplicated path logic.

DEM-error model: the error field is a spatially-autocorrelated Gaussian random
field (Hunter & Goodchild 1997). The default is a true **variogram** model
(exponential / spherical / gaussian, with an optional nugget), generated by FFT
spectral simulation — no `gstat`/geostatistics dependency, just `scipy.fft`. A
fast `"gaussian_filter"` approximation (white noise smoothed with a Gaussian
kernel) is kept as an option.
"""

import numpy as np
from scipy.fft import fft2, ifft2, next_fast_len
from scipy.ndimage import gaussian_filter
from scipy.sparse import csr_matrix

from .conductance import build_conductance
from .lcp import least_cost_path

_EPS = 1e-12
_VARIOGRAM_MODELS = ("exponential", "spherical", "gaussian")


def _covariance(h, vrange, model):
    """Unit-sill covariance at lag ``h`` (metres) for a variogram ``model``
    with practical range ``vrange``."""
    a = max(float(vrange), _EPS)
    if model == "exponential":
        return np.exp(-3.0 * h / a)
    if model == "gaussian":
        return np.exp(-3.0 * (h / a) ** 2)
    if model == "spherical":
        r = np.minimum(h / a, 1.0)
        return np.where(h <= a, 1.0 - 1.5 * r + 0.5 * r ** 3, 0.0)
    raise ValueError(
        "model must be one of %s or 'gaussian_filter'" % (_VARIOGRAM_MODELS,))


def simulate_error_field(shape, rmse, vrange, cellsize, rng,
                         model="exponential", nugget=0.0):
    """A spatially-autocorrelated Gaussian random field via FFT spectral
    simulation (Hunter & Goodchild 1997 / Dietrich & Newsam circulant embedding).

    Parameters
    ----------
    shape : (rows, cols).
    rmse : target standard deviation (sill = rmse**2).
    vrange : variogram practical range in metres.
    cellsize : metres per pixel.
    rng : numpy.random.Generator.
    model : "exponential" (default), "spherical" or "gaussian".
    nugget : fraction in [0, 1) of the variance that is spatially uncorrelated.

    Returns a ``shape`` ndarray with mean 0 and std == ``rmse``.
    """
    if model not in _VARIOGRAM_MODELS:
        raise ValueError(
            "model must be one of %s or 'gaussian_filter'" % (_VARIOGRAM_MODELS,))
    if not 0.0 <= nugget < 1.0:
        raise ValueError("nugget must be in [0, 1)")

    rows, cols = shape
    # Pad to a torus larger than the grid + range (circulant embedding) so the
    # periodic FFT does not wrap correlation across the edges.
    range_cells = int(np.ceil(vrange / cellsize)) if cellsize else 0
    nr = next_fast_len(rows + range_cells)
    nc = next_fast_len(cols + range_cells)

    iy = np.minimum(np.arange(nr), nr - np.arange(nr)) * cellsize
    ix = np.minimum(np.arange(nc), nc - np.arange(nc)) * cellsize
    lag = np.hypot(iy[:, None], ix[None, :])

    spectrum = fft2(_covariance(lag, vrange, model)).real
    np.clip(spectrum, 0.0, None, out=spectrum)
    amplitude = np.sqrt(spectrum)

    z = rng.standard_normal((nr, nc)) + 1j * rng.standard_normal((nr, nc))
    field = ifft2(amplitude * z).real[:rows, :cols]

    field -= field.mean()
    std = field.std()
    structured = field / std if std > 0 else field
    if nugget > 0.0:
        white = rng.standard_normal((rows, cols))
        out = np.sqrt(1.0 - nugget) * structured + np.sqrt(nugget) * white
    else:
        out = structured

    out -= out.mean()
    std = out.std()
    if std > 0:
        out = out / std * rmse
    return out


def add_dem_error(dem, rmse, autocorr_range, cellsize, rng,
                  model="exponential", nugget=0.0):
    """Return ``dem`` plus a spatially-correlated Gaussian error field.

    Parameters
    ----------
    dem : 2D float ndarray (elevations, metres); NoData as NaN is preserved.
    rmse : float, target vertical RMSE in metres (<= 0 returns ``dem`` unchanged).
    autocorr_range : float, spatial autocorrelation range in metres.
    cellsize : float, metres per pixel.
    rng : numpy.random.Generator.
    model : variogram model — "exponential" (default), "spherical", "gaussian",
        or "gaussian_filter" for the fast white-noise + Gaussian-kernel
        approximation.
    nugget : fraction in [0, 1) of spatially-uncorrelated variance (variogram
        models only).
    """
    if rmse <= 0:
        return dem

    finite = np.isfinite(dem)
    if model == "gaussian_filter":
        noise = rng.standard_normal(dem.shape)
        sigma = ((autocorr_range / cellsize)
                 if (autocorr_range > 0 and cellsize) else 0.0)
        if sigma > 0:
            noise = gaussian_filter(noise, sigma=sigma, mode="nearest")
    else:
        noise = simulate_error_field(
            dem.shape, rmse, autocorr_range, cellsize, rng,
            model=model, nugget=nugget)

    # Rescale so the error over the valid area has standard deviation = rmse.
    std = noise[finite].std() if finite.any() else 0.0
    if std > 0:
        noise = noise / std * rmse

    out = dem.copy()
    out[finite] = dem[finite] + noise[finite]
    return out


def add_global_stochasticity(matrix, drop_fraction, rng):
    """Return a copy of ``matrix`` with a random fraction of edges removed.

    Each directed edge is independently dropped with probability
    ``drop_fraction`` (0 returns the matrix unchanged; 1 removes every edge).
    Dropping edges can disconnect origin from destination in a given
    realisation — that iteration then contributes no path, which is the intended
    behaviour.
    """
    if drop_fraction <= 0:
        return matrix
    coo = matrix.tocoo(copy=False)
    keep = rng.random(coo.data.shape[0]) >= drop_fraction
    return csr_matrix(
        (coo.data[keep], (coo.row[keep], coo.col[keep])), shape=coo.shape)


def _jitter_params(cost_params, jitter, rng):
    """Multiply each cost parameter by an independent uniform(1-j, 1+j) factor."""
    if not cost_params:
        return cost_params
    factors = rng.uniform(1.0 - jitter, 1.0 + jitter, size=len(cost_params))
    return {k: v * f for (k, v), f in zip(cost_params.items(), factors)}


def _max_std_error(prob, k):
    """Max binomial standard error of a probability map after ``k`` trials."""
    return float(np.sqrt(np.max(prob * (1.0 - prob)) / k)) if k > 0 else np.inf


def stochastic_lcp(dem, cellsize, cost_fn, origin, destinations, n_iter, rng,
                   rmse=0.0, autocorr_range=0.0, drop_fraction=0.0,
                   neighbours=8, multiplier=None, progress=None,
                   cost_params=None, error_model="exponential", nugget=0.0,
                   cost_fns=None, cost_weights=None, param_jitter=0.0,
                   tol=None, convergence="stabilisation", min_iter=20,
                   check_every=10, patience=2, on_check=None,
                   return_diagnostics=False):
    """Probabilistic least-cost corridor over N stochastic realisations.

    Returns ``(prob, n_cells)`` where ``prob[i]`` is the fraction of the
    realisations in which cell ``i`` lay on a least-cost path from ``origin`` to
    any of ``destinations`` (a value in [0, 1]).

    Sources of variation per iteration, all optional and combinable:

    * **DEM error** (``rmse > 0``) — a variogram error field perturbs the DEM;
    * **edge dropping** (``drop_fraction > 0``);
    * **cost-model uncertainty** — sample a cost function from ``cost_fns``
      (uniform, or by ``cost_weights``) and/or jitter ``cost_params`` by
      ``±param_jitter`` (Herzog 2022: there is no universal best cost model).

    ``cost_fns`` defaults to ``[cost_fn]``. With a single cost function and no
    parameter jitter, behaviour (and the RNG stream) is unchanged. When neither
    the DEM nor the parameters vary, one conductance matrix per cost function is
    built once and reused.

    Convergence: ``n_iter`` is the **maximum** number of realisations. When
    ``tol`` is set the loop stops early once the corridor is good enough (checked
    every ``check_every`` iterations, never before ``min_iter``):

    * ``convergence="stabilisation"`` — stop once ``max|Δp|`` between successive
      checkpoints stays below ``tol`` for ``patience`` consecutive checks;
    * ``convergence="precision"`` — stop once ``max √(p(1-p)/k) < tol``.

    ``progress`` is a callable(fraction); ``on_check`` a callable(iterations,
    metric, ok) invoked at each convergence check. With ``return_diagnostics``,
    also returns ``diag = {iterations, converged, metric, criterion}``.
    """
    if n_iter < 1:
        raise ValueError("n_iter must be >= 1")
    if tol is not None and convergence not in ("stabilisation", "precision"):
        raise ValueError(
            "convergence must be 'stabilisation' or 'precision'")

    rows, cols = dem.shape
    n_cells = rows * cols
    if np.isscalar(destinations):
        destinations = [destinations]

    fns = list(cost_fns) if cost_fns else [cost_fn]
    n_fns = len(fns)
    weights = None
    if cost_weights is not None:
        weights = np.asarray(cost_weights, dtype=float)
        if weights.shape != (n_fns,) or np.any(weights < 0) or weights.sum() <= 0:
            raise ValueError(
                "cost_weights must be non-negative, one per cost function, "
                "with a positive sum")
        weights = weights / weights.sum()

    fixed_matrix = rmse <= 0 and param_jitter <= 0
    static = None
    if fixed_matrix:
        static = [build_conductance(
            dem, cellsize, fn, neighbours=neighbours, multiplier=multiplier,
            cost_params=cost_params)[0] for fn in fns]

    freq = np.zeros(n_cells, dtype=np.float64)
    iterations = n_iter
    converged = False
    metric = np.inf
    prev_map = None
    below = 0

    for k in range(1, n_iter + 1):
        idx = 0 if n_fns == 1 else int(rng.choice(n_fns, p=weights))
        if fixed_matrix:
            matrix = static[idx]
        else:
            cp = (_jitter_params(cost_params, param_jitter, rng)
                  if param_jitter > 0 else cost_params)
            dem_k = (add_dem_error(dem, rmse, autocorr_range, cellsize, rng,
                                   model=error_model, nugget=nugget)
                     if rmse > 0 else dem)
            matrix = build_conductance(
                dem_k, cellsize, fns[idx],
                neighbours=neighbours, multiplier=multiplier, cost_params=cp)[0]

        if drop_fraction > 0:
            matrix = add_global_stochasticity(matrix, drop_fraction, rng)

        on_path = np.zeros(n_cells, dtype=bool)
        for dest in destinations:
            nodes, _ = least_cost_path(matrix, origin, dest)
            on_path[nodes] = True
        freq[on_path] += 1.0

        if progress:
            progress(k / n_iter)

        if tol and k >= min_iter and k % check_every == 0:
            cur = freq / k
            if convergence == "precision":
                metric = _max_std_error(cur, k)
                ok = metric < tol
            else:
                metric = (np.inf if prev_map is None
                          else float(np.max(np.abs(cur - prev_map))))
                prev_map = cur
                ok = metric < tol
            if on_check:
                on_check(k, metric, ok)
            if convergence == "precision":
                if ok:
                    converged = True
            else:
                below = below + 1 if ok else 0
                converged = below >= patience
            if converged:
                iterations = k
                break

    prob = freq / iterations
    if return_diagnostics:
        return prob, n_cells, {
            "iterations": iterations, "converged": converged,
            "metric": metric, "criterion": convergence if tol else None}
    return prob, n_cells
