# -*- coding: utf-8 -*-
"""Stochastic least-cost paths (Lewis 2021).

Two sources of uncertainty are modelled and combined over N Monte-Carlo
realisations to produce a *probabilistic corridor* — the fraction of iterations
in which each cell lies on the least-cost path:

* **DEM error** — a vertical-accuracy (RMSE) error field is added to the DEM
  each iteration, so the slope (and therefore the cost surface) varies.
* **Global stochasticity** — edges are randomly dropped each iteration, modelling
  unmodelled local impassability.

Both are pure numpy/scipy and reuse the deterministic core (`build_conductance`,
`least_cost_path`), so there is no duplicated path logic.

DEM-error model: the error field is a spatially-autocorrelated Gaussian random
field (Hunter & Goodchild 1997). The default is a true **variogram** model
(exponential / spherical / gaussian, with an optional nugget), generated by FFT
spectral simulation — no `gstat`/geostatistics dependency, just `scipy.fft`. A
fast `"gaussian_filter"` approximation (white noise smoothed with a Gaussian
kernel) is kept as an option.
"""

import numpy as np
from scipy.fft import fft2, ifft2, next_fast_len
from scipy.ndimage import gaussian_filter
from scipy.sparse import csr_matrix

from .conductance import build_conductance
from .lcp import least_cost_path

_EPS = 1e-12
_VARIOGRAM_MODELS = ("exponential", "spherical", "gaussian")


def _covariance(h, vrange, model):
    """Unit-sill covariance at lag ``h`` (metres) for a variogram ``model``
    with practical range ``vrange``."""
    a = max(float(vrange), _EPS)
    if model == "exponential":
        return np.exp(-3.0 * h / a)
    if model == "gaussian":
        return np.exp(-3.0 * (h / a) ** 2)
    if model == "spherical":
        r = np.minimum(h / a, 1.0)
        return np.where(h <= a, 1.0 - 1.5 * r + 0.5 * r ** 3, 0.0)
    raise ValueError(
        "model must be one of %s or 'gaussian_filter'" % (_VARIOGRAM_MODELS,))


def simulate_error_field(shape, rmse, vrange, cellsize, rng,
                         model="exponential", nugget=0.0):
    """A spatially-autocorrelated Gaussian random field via FFT spectral
    simulation (Hunter & Goodchild 1997 / Dietrich & Newsam circulant embedding).

    Parameters
    ----------
    shape : (rows, cols).
    rmse : target standard deviation (sill = rmse**2).
    vrange : variogram practical range in metres.
    cellsize : metres per pixel.
    rng : numpy.random.Generator.
    model : "exponential" (default), "spherical" or "gaussian".
    nugget : fraction in [0, 1) of the variance that is spatially uncorrelated.

    Returns a ``shape`` ndarray with mean 0 and std == ``rmse``.
    """
    if model not in _VARIOGRAM_MODELS:
        raise ValueError(
            "model must be one of %s or 'gaussian_filter'" % (_VARIOGRAM_MODELS,))
    if not 0.0 <= nugget < 1.0:
        raise ValueError("nugget must be in [0, 1)")

    rows, cols = shape
    # Pad to a torus larger than the grid + range (circulant embedding) so the
    # periodic FFT does not wrap correlation across the edges.
    range_cells = int(np.ceil(vrange / cellsize)) if cellsize else 0
    nr = next_fast_len(rows + range_cells)
    nc = next_fast_len(cols + range_cells)

    iy = np.minimum(np.arange(nr), nr - np.arange(nr)) * cellsize
    ix = np.minimum(np.arange(nc), nc - np.arange(nc)) * cellsize
    lag = np.hypot(iy[:, None], ix[None, :])

    spectrum = fft2(_covariance(lag, vrange, model)).real
    np.clip(spectrum, 0.0, None, out=spectrum)
    amplitude = np.sqrt(spectrum)

    z = rng.standard_normal((nr, nc)) + 1j * rng.standard_normal((nr, nc))
    field = ifft2(amplitude * z).real[:rows, :cols]

    field -= field.mean()
    std = field.std()
    structured = field / std if std > 0 else field
    if nugget > 0.0:
        white = rng.standard_normal((rows, cols))
        out = np.sqrt(1.0 - nugget) * structured + np.sqrt(nugget) * white
    else:
        out = structured

    out -= out.mean()
    std = out.std()
    if std > 0:
        out = out / std * rmse
    return out


def add_dem_error(dem, rmse, autocorr_range, cellsize, rng,
                  model="exponential", nugget=0.0):
    """Return ``dem`` plus a spatially-correlated Gaussian error field.

    Parameters
    ----------
    dem : 2D float ndarray (elevations, metres); NoData as NaN is preserved.
    rmse : float, target vertical RMSE in metres (<= 0 returns ``dem`` unchanged).
    autocorr_range : float, spatial autocorrelation range in metres.
    cellsize : float, metres per pixel.
    rng : numpy.random.Generator.
    model : variogram model — "exponential" (default), "spherical", "gaussian",
        or "gaussian_filter" for the fast white-noise + Gaussian-kernel
        approximation.
    nugget : fraction in [0, 1) of spatially-uncorrelated variance (variogram
        models only).
    """
    if rmse <= 0:
        return dem

    finite = np.isfinite(dem)
    if model == "gaussian_filter":
        noise = rng.standard_normal(dem.shape)
        sigma = ((autocorr_range / cellsize)
                 if (autocorr_range > 0 and cellsize) else 0.0)
        if sigma > 0:
            noise = gaussian_filter(noise, sigma=sigma, mode="nearest")
    else:
        noise = simulate_error_field(
            dem.shape, rmse, autocorr_range, cellsize, rng,
            model=model, nugget=nugget)

    # Rescale so the error over the valid area has standard deviation = rmse.
    std = noise[finite].std() if finite.any() else 0.0
    if std > 0:
        noise = noise / std * rmse

    out = dem.copy()
    out[finite] = dem[finite] + noise[finite]
    return out


def add_global_stochasticity(matrix, drop_fraction, rng):
    """Return a copy of ``matrix`` with a random fraction of edges removed.

    Each directed edge is independently dropped with probability
    ``drop_fraction`` (0 returns the matrix unchanged; 1 removes every edge).
    Dropping edges can disconnect origin from destination in a given
    realisation — that iteration then contributes no path, which is the intended
    behaviour.
    """
    if drop_fraction <= 0:
        return matrix
    coo = matrix.tocoo(copy=False)
    keep = rng.random(coo.data.shape[0]) >= drop_fraction
    return csr_matrix(
        (coo.data[keep], (coo.row[keep], coo.col[keep])), shape=coo.shape)


def stochastic_lcp(dem, cellsize, cost_fn, origin, destinations, n_iter, rng,
                   rmse=0.0, autocorr_range=0.0, drop_fraction=0.0,
                   neighbours=8, multiplier=None, progress=None,
                   cost_params=None, error_model="exponential", nugget=0.0):
    """Probabilistic least-cost corridor over N stochastic realisations.

    Returns ``(prob, n_cells)`` where ``prob[i]`` is the fraction of the
    ``n_iter`` realisations in which cell ``i`` lay on a least-cost path from
    ``origin`` to any of ``destinations`` (a value in [0, 1]).

    When ``rmse <= 0`` the conductance matrix is built once and reused (only edge
    dropping varies); otherwise it is rebuilt each iteration on a freshly
    perturbed DEM. ``progress`` is an optional callable(fraction_0_to_1).
    """
    if n_iter < 1:
        raise ValueError("n_iter must be >= 1")

    rows, cols = dem.shape
    n_cells = rows * cols
    if np.isscalar(destinations):
        destinations = [destinations]

    static_matrix = None
    if rmse <= 0:
        static_matrix, _, _ = build_conductance(
            dem, cellsize, cost_fn, neighbours=neighbours, multiplier=multiplier,
            cost_params=cost_params)

    freq = np.zeros(n_cells, dtype=np.float64)

    for k in range(n_iter):
        if static_matrix is None:
            dem_k = add_dem_error(dem, rmse, autocorr_range, cellsize, rng,
                                  model=error_model, nugget=nugget)
            matrix = build_conductance(
                dem_k, cellsize, cost_fn,
                neighbours=neighbours, multiplier=multiplier,
                cost_params=cost_params)[0]
        else:
            matrix = static_matrix

        if drop_fraction > 0:
            matrix = add_global_stochasticity(matrix, drop_fraction, rng)

        on_path = np.zeros(n_cells, dtype=bool)
        for dest in destinations:
            nodes, _ = least_cost_path(matrix, origin, dest)
            on_path[nodes] = True
        freq[on_path] += 1.0

        if progress:
            progress((k + 1) / n_iter)

    return freq / n_iter, n_cells
